version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/theme/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
